apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: tickets-tickets-reserved-trigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: Tickets.Reserved
  subscriber:
    uri: http://tickets-service.default.svc.cluster.local/reserve

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: tickets-tickets-payment-requested-trigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: Tickets.PaymentRequested
  subscriber:
    uri: http://tickets-service.default.svc.cluster.local/checkout

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: tickets-tickets-emitted-trigger
  namespace: default
spec:
  broker: default
  filter:
    attributes:
      type: Tickets.Emitted
  subscriber:
    uri: http://tickets-service.default.svc.cluster.local/emit